spring.application.name=Doacao
# Habilita o console web do H2 para você visualizar as tabelas no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Configuração da conexão (muda o nome do banco para 'meubanco')
spring.datasource.url=jdbc:h2:mem:db_doacao
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Mantém o banco vivo enquanto a aplicação estiver rodando
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect