/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec.poo;

import edu.fatec.poo.persistence.connection.CurrentConnection;
import edu.fatec.poo.views.UICoodenator;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        CurrentConnection currentConnection = new CurrentConnection();
        Application.launch(App.class, args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        UICoodenator coodenator = new UICoodenator(primaryStage);
        coodenator.showLoginScreen();
    }
}
