/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec.poo;

import edu.fatec.poo.persistence.CurrentConnection;
import edu.fatec.poo.views.person.UICadastrarPessoa;
import edu.fatec.poo.views.user.UIUserLogin;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        CurrentConnection currentConnection = new CurrentConnection();
        Application.launch(UIUserLogin.class, args);
    }
}
