/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec.poo;

import atlantafx.base.theme.NordDark;
import edu.fatec.poo.model.Usuario;
import edu.fatec.poo.persistence.connection.CurrentConnection;
import edu.fatec.poo.views.UICoordenador;
import javafx.application.Application;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        Application.setUserAgentStylesheet(new NordDark().getUserAgentStylesheet());
        Application.launch(App.class, args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        UICoordenador coodenator = new UICoordenador(primaryStage);
        {
            CurrentConnection connection = new CurrentConnection();
            connection.buildMariaDb();
        }
        coodenator.showCadastroDoacaoScreen(new Usuario());
        //coodenator.showLoginScreen();
    }
}
